[project]
name = "api-work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "flask>=3.1.2",
    "jupyter>=1.1.1",
    "nbformat>=5.10.4",
    "pyd>=0.13.1",
    "uvicorn>=0.40.0",
]
